[[features]]
  title = "Kidical Mass Matosinhos"
  sub_title = "Partida do percurso 1"
  location_name = "Igreja de São Mamede de Infesta"
  date = "22 de outubro"
  time = "15h"
  latitude = 41.1927351
  longitude = -8.6099548

[[features]]
  title = "Kidical Mass Matosinhos"
  sub_title = "Partida do percurso 2"
  location_name = "Escola EB Eng. Fernando Pinto de Oliveira"
  date = "22 de outubro"
  time = "15:30h"
  latitude = 41.1982749
  longitude = -8.7061225

 [[features]]
  title = "Kidical Mass Matosinhos"
  sub_title = "Encontro e percurso conjunto"
  location_name = "Jardim Basílio Teles"
  date = "22 de outubro"
  time = "16h"
  latitude = 41.1816435
  longitude = -8.6873642
